name: Run Action When Project Status Changes to QA

on:
  workflow_dispatch:
  project_card:
    types:
      - moved

jobs:
  check-project-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check if project status changed to QA
        id: check_status
        uses: actions/github-script@v6
        with:
          script: |
            const projectCard = context.payload.project_card;

            if (!projectCard || !projectCard.column_id) {
              console.log("No project card or column change detected.");
              return false;
            }

            const columnId = projectCard.column_id;
            const qaColumnId = "e449b8e2";

            return columnId === qaColumnId;

      - name: Get current assignees
        id: get_assignees
        if: steps.check_status.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const issueUrl = context.payload.project_card.content_url;

            if (!issueUrl.includes('/issues/')) {
              console.log("This card is not linked to an issue.");
              return [];
            }

            const issueNumber = issueUrl.split('/').pop();
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            return issue.data.assignees.map(assignee => assignee.login);

      - name: Assign user when status is QA
        if: steps.check_status.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const issueUrl = context.payload.project_card.content_url;

            if (!issueUrl.includes('/issues/')) {
              console.log("This card is not linked to an issue.");
              return;
            }

            const issueNumber = issueUrl.split('/').pop();
            const currentAssignees = JSON.parse(process.env.CURRENT_ASSIGNEES || "[]");
            const newAssignee = "Geonpyo999";
            // Combine current assignees and new assignee without duplicates
            const updatedAssignees = [...new Set([...currentAssignees, newAssignee])];

            // Add assignees to the issue
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: updatedAssignees,
            });
        env:
          CURRENT_ASSIGNEES: ${{ steps.get_assignees.outputs.result }}
